---

- name: install aptitude
  apt: 
    name: aptitude
    state: present
    force_apt_get: true
    update_cache: yes
    cache_valid_time: 3600

- name: update apt packages
  apt:
    name: '*'
    state: latest
    update_cache: yes
    cache_valid_time: 3600
    autoclean: yes
    autoremove: yes
  when: full_update_apt_packages

- name: install packages from provided list
  apt: 
    name: "{{ debian_package_list }}" 
    state: present